// <auto-generated />
using System;
using LIP.Infrastructure.Persistency;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LIP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251022141435_UpdateTableName")]
    partial class UpdateTableName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ExamPracticeQuestion", b =>
                {
                    b.Property<int>("ExamsExamId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionsQuestionId")
                        .HasColumnType("int");

                    b.HasKey("ExamsExamId", "QuestionsQuestionId");

                    b.HasIndex("QuestionsQuestionId");

                    b.ToTable("ExamPracticeQuestion");
                });

            modelBuilder.Entity("LIP.Domain.Entities.AnswerGuide", b =>
                {
                    b.Property<int>("AnswerGuideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AnswerGuideId"));

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KeyPoints")
                        .HasColumnType("longtext");

                    b.Property<int?>("MaxScore")
                        .HasColumnType("int");

                    b.HasKey("AnswerGuideId");

                    b.HasIndex("ExamId");

                    b.ToTable("AnswerGuides");
                });

            modelBuilder.Entity("LIP.Domain.Entities.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByNavigationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("ExamTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("GradeLevelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MatrixId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("ExamId");

                    b.HasIndex("CreatedByNavigationUserId");

                    b.HasIndex("ExamTypeId");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex("MatrixId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("LIP.Domain.Entities.ExamAnswer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AnswerContent")
                        .HasColumnType("longtext");

                    b.Property<int?>("AttemptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("AnswerId");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ExamAnswers");
                });

            modelBuilder.Entity("LIP.Domain.Entities.ExamAttempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AttemptId"));

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSavedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AttemptId");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("ExamAttempts");
                });

            modelBuilder.Entity("LIP.Domain.Entities.ExamMatrix", b =>
                {
                    b.Property<int>("MatrixId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MatrixId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByNavigationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("GradeLevelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("MatrixId");

                    b.HasIndex("CreatedByNavigationUserId");

                    b.HasIndex("GradeLevelId");

                    b.ToTable("ExamMatrices");
                });

            modelBuilder.Entity("LIP.Domain.Entities.ExamMatrixDetail", b =>
                {
                    b.Property<int>("ExamMatrixDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ExamMatrixDetailId"));

                    b.Property<string>("Difficulty")
                        .HasColumnType("longtext");

                    b.Property<int?>("ExamMatricId")
                        .HasColumnType("int");

                    b.Property<int?>("ExamMatrixMatrixId")
                        .HasColumnType("int");

                    b.Property<string>("LessonName")
                        .HasColumnType("longtext");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("QuestionType")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ScorePerQuestion")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ExamMatrixDetailId");

                    b.HasIndex("ExamMatrixMatrixId");

                    b.ToTable("ExamMatrixDetails");
                });

            modelBuilder.Entity("LIP.Domain.Entities.ExamType", b =>
                {
                    b.Property<int>("ExamTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ExamTypeId"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("ExamTypeId");

                    b.ToTable("ExamTypes");
                });

            modelBuilder.Entity("LIP.Domain.Entities.GradeLevel", b =>
                {
                    b.Property<int>("GradeLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GradeLevelId"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("GradeLevelId");

                    b.ToTable("GradeLevels");
                });

            modelBuilder.Entity("LIP.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LIP.Domain.Entities.PracticeQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("Answer")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByNavigationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Difficulty")
                        .HasColumnType("longtext");

                    b.Property<int?>("GradeLevelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("QuestionType")
                        .HasColumnType("longtext");

                    b.HasKey("QuestionId");

                    b.HasIndex("CreatedByNavigationUserId");

                    b.HasIndex("GradeLevelId");

                    b.ToTable("PracticeQuestions");
                });

            modelBuilder.Entity("LIP.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LIP.Domain.Entities.Template", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByNavigationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext");

                    b.Property<int?>("GradeLevelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("TemplateId");

                    b.HasIndex("CreatedByNavigationUserId");

                    b.HasIndex("GradeLevelId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("LIP.Domain.Entities.TemplateOrder", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("TemplateOrders");
                });

            modelBuilder.Entity("LIP.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExamPracticeQuestion", b =>
                {
                    b.HasOne("LIP.Domain.Entities.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamsExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LIP.Domain.Entities.PracticeQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionsQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIP.Domain.Entities.AnswerGuide", b =>
                {
                    b.HasOne("LIP.Domain.Entities.Exam", "Exam")
                        .WithMany("Answerguides")
                        .HasForeignKey("ExamId");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("LIP.Domain.Entities.Exam", b =>
                {
                    b.HasOne("LIP.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Exams")
                        .HasForeignKey("CreatedByNavigationUserId");

                    b.HasOne("LIP.Domain.Entities.ExamType", "ExamType")
                        .WithMany("Exams")
                        .HasForeignKey("ExamTypeId");

                    b.HasOne("LIP.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany("Exams")
                        .HasForeignKey("GradeLevelId");

                    b.HasOne("LIP.Domain.Entities.ExamMatrix", "Matrix")
                        .WithMany("Exams")
                        .HasForeignKey("MatrixId");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ExamType");

                    b.Navigation("GradeLevel");

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("LIP.Domain.Entities.ExamAnswer", b =>
                {
                    b.HasOne("LIP.Domain.Entities.ExamAttempt", "Attempt")
                        .WithMany("Examanswers")
                        .HasForeignKey("AttemptId");

                    b.HasOne("LIP.Domain.Entities.PracticeQuestion", "Question")
                        .WithMany("Examanswers")
                        .HasForeignKey("QuestionId");

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LIP.Domain.Entities.ExamAttempt", b =>
                {
                    b.HasOne("LIP.Domain.Entities.Exam", "Exam")
                        .WithMany("Examattempts")
                        .HasForeignKey("ExamId");

                    b.HasOne("LIP.Domain.Entities.User", "User")
                        .WithMany("Examattempts")
                        .HasForeignKey("UserId");

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LIP.Domain.Entities.ExamMatrix", b =>
                {
                    b.HasOne("LIP.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Exammatrices")
                        .HasForeignKey("CreatedByNavigationUserId");

                    b.HasOne("LIP.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany("Exammatrices")
                        .HasForeignKey("GradeLevelId");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("GradeLevel");
                });

            modelBuilder.Entity("LIP.Domain.Entities.ExamMatrixDetail", b =>
                {
                    b.HasOne("LIP.Domain.Entities.ExamMatrix", "ExamMatrix")
                        .WithMany("Exammatrixdetails")
                        .HasForeignKey("ExamMatrixMatrixId");

                    b.Navigation("ExamMatrix");
                });

            modelBuilder.Entity("LIP.Domain.Entities.Payment", b =>
                {
                    b.HasOne("LIP.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LIP.Domain.Entities.PracticeQuestion", b =>
                {
                    b.HasOne("LIP.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Practicequestions")
                        .HasForeignKey("CreatedByNavigationUserId");

                    b.HasOne("LIP.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany("Practicequestions")
                        .HasForeignKey("GradeLevelId");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("GradeLevel");
                });

            modelBuilder.Entity("LIP.Domain.Entities.Template", b =>
                {
                    b.HasOne("LIP.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Templates")
                        .HasForeignKey("CreatedByNavigationUserId");

                    b.HasOne("LIP.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany("Templates")
                        .HasForeignKey("GradeLevelId");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("GradeLevel");
                });

            modelBuilder.Entity("LIP.Domain.Entities.TemplateOrder", b =>
                {
                    b.HasOne("LIP.Domain.Entities.Payment", "Payment")
                        .WithMany("Templatebookings")
                        .HasForeignKey("PaymentId");

                    b.HasOne("LIP.Domain.Entities.Template", "Template")
                        .WithMany("Templatebookings")
                        .HasForeignKey("TemplateId");

                    b.HasOne("LIP.Domain.Entities.User", "User")
                        .WithMany("Templatebookings")
                        .HasForeignKey("UserId");

                    b.Navigation("Payment");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LIP.Domain.Entities.User", b =>
                {
                    b.HasOne("LIP.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LIP.Domain.Entities.Exam", b =>
                {
                    b.Navigation("Answerguides");

                    b.Navigation("Examattempts");
                });

            modelBuilder.Entity("LIP.Domain.Entities.ExamAttempt", b =>
                {
                    b.Navigation("Examanswers");
                });

            modelBuilder.Entity("LIP.Domain.Entities.ExamMatrix", b =>
                {
                    b.Navigation("Exammatrixdetails");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("LIP.Domain.Entities.ExamType", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("LIP.Domain.Entities.GradeLevel", b =>
                {
                    b.Navigation("Exammatrices");

                    b.Navigation("Exams");

                    b.Navigation("Practicequestions");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("LIP.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Templatebookings");
                });

            modelBuilder.Entity("LIP.Domain.Entities.PracticeQuestion", b =>
                {
                    b.Navigation("Examanswers");
                });

            modelBuilder.Entity("LIP.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LIP.Domain.Entities.Template", b =>
                {
                    b.Navigation("Templatebookings");
                });

            modelBuilder.Entity("LIP.Domain.Entities.User", b =>
                {
                    b.Navigation("Examattempts");

                    b.Navigation("Exammatrices");

                    b.Navigation("Exams");

                    b.Navigation("Payments");

                    b.Navigation("Practicequestions");

                    b.Navigation("Templatebookings");

                    b.Navigation("Templates");
                });
#pragma warning restore 612, 618
        }
    }
}
